# docker-compose.yml
version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - nginx_cache:/var/cache/nginx
    depends_on:
      - go-app
      - python-app

  go-app:
    build: ./app1_golang

  python-app:
    build: ./app2_python
    environment:
      - FLASK_APP=app.py

volumes:
  nginx_cache: